In [ ]:
import numpy as np
A = np.array([
    [2, -1],
    [0, 3]
])  
B = np.array([
    [1, 2],
    [-3, 4]
])
print("A+B is:\n",A+B)
print("AB is:\n",A@B)
print("3A-2B is:\n",3*A - 2*B)

A+B is:
 [[ 3  1]
 [-3  7]]
AB is:
 [[ 5  0]
 [-9 12]]
3A-2B is :
 [[ 4 -7]
 [ 6  1]]


In [17]:
print("Determinant of A is:", np.linalg.det(A))

Determinant of A is: 6.0


In [18]:
if(np.linalg.det(A) != 0):
    print("Matrix A is invertible")
    A_1 = np.linalg.inv(A)
    print("Inverse of A:\n", A_1)

Matrix A is invertible
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


In [ ]:
C=np.array([
    [4,1],
    [-2,1]
    ])
eigenvalues, eigenvectors = np.linalg.eig(C)
for i in range(len(eigenvalues)):
    print(f"Eigenvalue {i+1}:", eigenvalues[i])
    print(f"Eigenvector {i+1}:", eigenvectors[:, i])

Matrix A:
[[ 2 -1]
 [ 0  3]]

Eigenvalue (first):
2.0

Corresponding Eigenvector:
[1. 0.]


In [19]:
X= np.array([
    [4, 1.5, 100],
    [6, 2.0, 150]
])
y = np.array([20, 30])
Beta= np.linalg.pinv(X.T @ X) @ X.T @ y
print("For given dataset, regression coefficient(Beta) is:", Beta)
Test_Car= np.array([8, 3, 200])
Price_Predicted = Test_Car @ Beta
print("Predicted Price of Test Car:", Price_Predicted)

For given dataset, regression coefficient(Beta) is: [ 7.98722045e-03 -4.12114787e-13  1.99680511e-01]
Predicted Price of Test Car: 39.99999999999998
